/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ma_test_InvokeC_Sample */

#ifndef _Included_com_ma_test_InvokeC_Sample
#define _Included_com_ma_test_InvokeC_Sample
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
